---
  - name: Tasks for remaining prereq on all the hosts
    hosts: cluster:ipaserver
    become: yes
    become_user: root
    roles:
    - cdp_base_OS_prereq 

  - name: Tasks for packages installation on all the CDP Base hosts
    hosts: cluster
    become: yes
    become_user: root
    tasks:
      - name: install packages
        yum:
          name:
           - ipa-client
           - wget
           - ntp
           
  - name: Tasks for packages installation on the freeipa server
    hosts: ipaserver
    become: yes
    become_user: root
    tasks:
      - name: install packages
        yum:
          name:
           - wget
           - ntp

  - name: Reboot the freeipa server
    hosts: ipaserver
    become: yes
    become_user: root
    tasks:
      - name: Reboot the FreeIPA server for Disabling SELinux
        ansible.builtin.reboot:       
        when: ansible_facts.selinux.status == 'enabled'        

  - name: Reboot all the worker nodes
    hosts: workers
    become: yes
    become_user: root
    tasks:
      - name: Reboot the machines
        ansible.builtin.reboot:
        when: ansible_facts.selinux.status == 'enabled'
