---
  - name: Tasks for remaining prereq on all the hosts
    hosts: cluster
    become: yes
    become_user: root
    pre_tasks:
      - name: install packages
        yum:
          name:
           - ipa-client
           - wget
           - ntp    
    roles:
    - cdp_base_OS_prereq    

  - name: Base Prereq on the freeipa server
    hosts: ipaserver
    become: yes
    become_user: root
    pre_tasks:
      - name: install packages
        yum:
          name:
           - wget
           - ntp
    roles:
    - cdp_base_OS_prereq
    post_tasks:
      - name: Reboot the FreeIPA server for Disabling SELinux
        shell: reboot
        when: ansible_facts.selinux.status == 'enabled'        

  - name: Reboot all the worker nodes
    hosts: workers
    become: yes
    become_user: root
    tasks:
      - name: Reboot the machines
        shell: reboot
        when: ansible_facts.selinux.status == 'enabled'