---
  - name: Tasks for remaining prereq on all the hosts
    hosts: cluster
    become: yes
    become_user: root
    tasks:
      - name: install packages
        yum:
          name:
           - ipa-client
           - wget
           - ntp
    include_role:
      name: cdp_base_OS_prereq    

  - name: Base Prereq on the freeipa server
    hosts: ipaserver
    become: yes
    become_user: root
    tasks:
      - name: install packages
        yum:
          name:
           - wget
           - ntp
    include_role:
      name: cdp_base_OS_prereq

  - name: Reboot the freeipa server
    hosts: ipaserver
    become: yes
    become_user: root
    tasks:
      - name: Reboot the FreeIPA server for Disabling SELinux
        ansible.builtin.reboot:       
        when: ansible_facts.selinux.status == 'enabled'        

  - name: Reboot all the worker nodes
    hosts: workers
    become: yes
    become_user: root
    tasks:
      - name: Reboot the machines
        ansible.builtin.reboot:
        when: ansible_facts.selinux.status == 'enabled'
