---
  - name: Master tasks for password less ssh
    hosts: master
    become: yes
    become_user: root
    roles:
    - master_node_password_less_ssh

  - name: Worker tasks for password less ssh
    hosts: workers
    become: yes
    become_user: root
    roles:
    - base_node_password_less_ssh

  - name: IPAServer tasks for password less ssh
    hosts: ipaserver
    become: yes
    become_user: root
    roles:
    - base_node_password_less_ssh